-- Schema migrations for Supabase

-- Create the users table
CREATE TABLE IF NOT EXISTS public.users (
    chat_id TEXT PRIMARY KEY,
    name TEXT,
    is_active INTEGER DEFAULT 1,
    alert_mode TEXT DEFAULT 'full',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create the keywords table
CREATE TABLE IF NOT EXISTS public.keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES public.users(chat_id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    term_normalized TEXT NOT NULL,
    max_price_cents INTEGER
);

-- Create index for faster matching and unique constraints
CREATE UNIQUE INDEX IF NOT EXISTS idx_keywords_user_term 
ON public.keywords(user_id, term_normalized);

-- Create the coupon_interests table
CREATE TABLE IF NOT EXISTS public.coupon_interests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES public.users(chat_id) ON DELETE CASCADE,
    store_name TEXT NOT NULL,
    store_normalized TEXT NOT NULL
);

-- Create index for faster matching and unique constraints
CREATE UNIQUE INDEX IF NOT EXISTS idx_coupon_interests_user_store 
ON public.coupon_interests(user_id, store_normalized);

-- Set Row Level Security (RLS) if needed (Optional, but recommended for Supabase)
-- Disable RLS for now since this is meant to be accessed by a secure server bot (using Service Role Key)
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_interests DISABLE ROW LEVEL SECURITY;
